<template><div><h1 id="周杰伦音乐作品全收录" tabindex="-1"><a class="header-anchor" href="#周杰伦音乐作品全收录"><span>周杰伦音乐作品全收录</span></a></h1>
<blockquote>
<p><em>世代的狂 音乐的王 万物沉浮在我乐章</em></p>
</blockquote>
<ul>
<li>建设中，目标：每张专辑有单独wiki页面，每首歌有单独wiki页面</li>
</ul>
<h3 id="录音室专辑" tabindex="-1"><a class="header-anchor" href="#录音室专辑"><span>录音室专辑</span></a></h3>
<table>
<thead>
<tr>
<th>序号</th>
<th>专辑名</th>
<th>发行时间</th>
<th>收听</th>
</tr>
</thead>
<tbody>
<tr>
<td>15</td>
<td>最伟大的作品</td>
<td>2022-07-15</td>
<td><a href="https://y.qq.com/n/ryqq/albumDetail/0042cH172YJ0mz" title="QQ音乐" target="_blank" rel="noopener noreferrer">QQ音乐</a> <a href="https://music.migu.cn/v3/music/digital_album/1139605801?from=migu" title="咪咕音乐" target="_blank" rel="noopener noreferrer">咪咕音乐</a> <a href="https://www.kugou.com/album/info/z1cd9a1/" title="酷狗音乐" target="_blank" rel="noopener noreferrer">酷狗音乐</a> <a href="https://kuwo.cn/album_detail/29593612" title="酷我音乐" target="_blank" rel="noopener noreferrer">酷我音乐</a> <br> <a href="https://music.apple.com/cn/album/%E6%9C%80%E4%BC%9F%E5%A4%A7%E7%9A%84%E4%BD%9C%E5%93%81/1633408719" title="AppleMusic Spotify" target="_blank" rel="noopener noreferrer">AppleMusic</a>  Spotify</td>
</tr>
<tr>
<td>14</td>
<td>周杰伦的床边故事</td>
<td>2016-06-24</td>
<td></td>
</tr>
<tr>
<td>13</td>
<td>哎呦不错哦</td>
<td>2014-12-26</td>
<td></td>
</tr>
<tr>
<td>12</td>
<td>十二新作</td>
<td>2012-12-28</td>
<td></td>
</tr>
<tr>
<td>11</td>
<td>惊叹号！</td>
<td>2011-11-11</td>
<td></td>
</tr>
<tr>
<td>10</td>
<td>跨时代</td>
<td>2010-05-18</td>
<td></td>
</tr>
<tr>
<td>9</td>
<td>魔杰座</td>
<td>2008-10-15</td>
<td></td>
</tr>
<tr>
<td>8</td>
<td>我很忙</td>
<td>2007-11-02</td>
<td></td>
</tr>
<tr>
<td>7</td>
<td>依然范特西</td>
<td>2006-09-05</td>
<td></td>
</tr>
<tr>
<td>6</td>
<td>11月的肖邦</td>
<td>2005-11-01</td>
<td></td>
</tr>
<tr>
<td>5</td>
<td>七里香</td>
<td>2004-08-03</td>
<td></td>
</tr>
<tr>
<td>4</td>
<td>叶惠美</td>
<td>2003-07-31</td>
<td></td>
</tr>
<tr>
<td>3</td>
<td>八度空间</td>
<td>2002-07-18</td>
<td></td>
</tr>
<tr>
<td>2</td>
<td>范特西</td>
<td>2001-09-14</td>
<td></td>
</tr>
<tr>
<td>1</td>
<td>Jay</td>
<td>2000-11-07</td>
<td></td>
</tr>
</tbody>
</table>
<h3 id="现场专辑" tabindex="-1"><a class="header-anchor" href="#现场专辑"><span>现场专辑</span></a></h3>
<table>
<thead>
<tr>
<th>专辑名</th>
<th>发行时间</th>
<th>收听</th>
</tr>
</thead>
<tbody>
<tr>
<td>周杰伦地表最强世界巡回演唱会</td>
<td>2019-11-01</td>
<td></td>
</tr>
<tr>
<td>周杰伦魔天伦世界巡回演唱会</td>
<td>2016-05-10</td>
<td></td>
</tr>
<tr>
<td>Thr Era 2010 超时代演唱会</td>
<td>2011-01-25</td>
<td></td>
</tr>
<tr>
<td>2007世界巡回演唱会</td>
<td>2008-01-30</td>
<td></td>
</tr>
<tr>
<td>周杰伦 2004 无与伦比 演唱会 Live CD</td>
<td>2005-01-20</td>
<td></td>
</tr>
<tr>
<td>The One 演唱会</td>
<td>2002-10-25</td>
<td></td>
</tr>
<tr>
<td>范特西PLUS</td>
<td>2001-12-28</td>
<td></td>
</tr>
</tbody>
</table>
<h3 id="ep" tabindex="-1"><a class="header-anchor" href="#ep"><span>EP</span></a></h3>
<table>
<thead>
<tr>
<th>专辑名</th>
<th>发行时间</th>
<th>收听</th>
</tr>
</thead>
<tbody>
<tr>
<td>霍元甲</td>
<td>2006-01-20</td>
<td></td>
</tr>
<tr>
<td>J III MP3 Player</td>
<td>2005-06-24</td>
<td></td>
</tr>
<tr>
<td>寻找周杰伦</td>
<td>2003-11-13</td>
<td></td>
</tr>
</tbody>
</table>
<h3 id="单曲" tabindex="-1"><a class="header-anchor" href="#单曲"><span>单曲</span></a></h3>
<table>
<thead>
<tr>
<th>歌曲名</th>
<th>发行时间</th>
<th>收听</th>
</tr>
</thead>
<tbody>
<tr>
<td>圣诞星（feat. 杨瑞代）</td>
<td></td>
<td></td>
</tr>
<tr>
<td>Mojito</td>
<td></td>
<td></td>
</tr>
<tr>
<td>我是如此相信</td>
<td></td>
<td></td>
</tr>
<tr>
<td>说好不哭（with 五月天阿信）</td>
<td></td>
<td></td>
</tr>
<tr>
<td>不爱我就拉倒</td>
<td></td>
<td></td>
</tr>
<tr>
<td>等你下课</td>
<td></td>
<td></td>
</tr>
<tr>
<td>英雄</td>
<td></td>
<td></td>
</tr>
<tr>
<td>Try</td>
<td></td>
<td></td>
</tr>
<tr>
<td>天地一斗</td>
<td></td>
<td></td>
</tr>
<tr>
<td>周大侠</td>
<td></td>
<td></td>
</tr>
<tr>
<td>千山万水</td>
<td></td>
<td></td>
</tr>
<tr>
<td>黄金甲</td>
<td></td>
<td></td>
</tr>
<tr>
<td>这所有的一切</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<h3 id="概念专辑" tabindex="-1"><a class="header-anchor" href="#概念专辑"><span>概念专辑</span></a></h3>
<table>
<thead>
<tr>
<th>专辑名</th>
<th>发行时间</th>
<th>收听</th>
</tr>
</thead>
<tbody>
<tr>
<td>The Crew 乐酷 概念合辑</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<h3 id="原声带" tabindex="-1"><a class="header-anchor" href="#原声带"><span>原声带</span></a></h3>
<table>
<thead>
<tr>
<th>专辑名</th>
<th>类型</th>
<th>发行时间</th>
<th>收听</th>
</tr>
</thead>
<tbody>
<tr>
<td>不能说的秘密电影原声带</td>
<td>电影原声带</td>
<td></td>
<td></td>
</tr>
<tr>
<td>天台电影原声带</td>
<td>电影原声带</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<h3 id="未发行" tabindex="-1"><a class="header-anchor" href="#未发行"><span>未发行</span></a></h3>
<table>
<thead>
<tr>
<th>专辑名</th>
<th>发行时间</th>
<th>收听</th>
</tr>
</thead>
<tbody>
<tr>
<td>纽约地铁</td>
<td>2022-08-29</td>
<td></td>
</tr>
<tr>
<td>大头贴</td>
<td>2006-01-12</td>
<td></td>
</tr>
<tr>
<td>我们在成长</td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td><img src="http://doc.cyfor.top/server/index.php?s=/api/attachment/visitFile&amp;sign=6f26d5b477f1ac6dad8de191f081500b" alt="" loading="lazy"></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<h3 id="合作献唱" tabindex="-1"><a class="header-anchor" href="#合作献唱"><span>合作献唱</span></a></h3>
<table>
<thead>
<tr>
<th>歌曲名</th>
<th>专辑名</th>
<th>合作歌手</th>
<th>发行时间</th>
<th>收听</th>
</tr>
</thead>
<tbody>
<tr>
<td>阿爸</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>画沙</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>你是我的OK绷</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<h3 id="写给其他歌手作品" tabindex="-1"><a class="header-anchor" href="#写给其他歌手作品"><span>写给其他歌手作品</span></a></h3>
<p><a href="http://111" title="写给其他歌手作品" target="_blank" rel="noopener noreferrer">写给其他歌手作品</a></p>
<h3 id="现场翻唱" tabindex="-1"><a class="header-anchor" href="#现场翻唱"><span>现场翻唱</span></a></h3>
<p><a href="http://111" title="现场翻唱" target="_blank" rel="noopener noreferrer">现场翻唱</a></p>
</div></template>


