import comp from "C:/Users/CYFOR/Desktop/zjl/wiki/jaychou-wiki/src/.vuepress/.temp/pages/about/index.html.vue"
const data = JSON.parse("{\"path\":\"/about/\",\"title\":\"关于本站\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"关于本站 关于JayChou's wiki 本站想法源于2024年4月，无意间查到jaychou.wiki域名可以注册，便注册了域名，在思考用来做什么的时候，看到了苏打盖，随即决定对前人进行学习模仿。 （使用了同一个开源前端框架和主题，并非copy😂） 互联网已经存在很多资料，为什么还要费神做一个网站 互联网精神”即：开放、平等、协作、快速、共享。它...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.jaychou.wiki/about/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"JayChou's wiki | 周杰伦百科资料集\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"关于本站\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"关于本站 关于JayChou's wiki 本站想法源于2024年4月，无意间查到jaychou.wiki域名可以注册，便注册了域名，在思考用来做什么的时候，看到了苏打盖，随即决定对前人进行学习模仿。 （使用了同一个开源前端框架和主题，并非copy😂） 互联网已经存在很多资料，为什么还要费神做一个网站 互联网精神”即：开放、平等、协作、快速、共享。它...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"JayChou's wiki\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"关于本站\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"JayChou's wiki\\\",\\\"url\\\":\\\"https://www.jaychou.wiki\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"关于JayChou's wiki\",\"slug\":\"关于jaychou-s-wiki\",\"link\":\"#关于jaychou-s-wiki\",\"children\":[]},{\"level\":2,\"title\":\"互联网已经存在很多资料，为什么还要费神做一个网站\",\"slug\":\"互联网已经存在很多资料-为什么还要费神做一个网站\",\"link\":\"#互联网已经存在很多资料-为什么还要费神做一个网站\",\"children\":[]}],\"readingTime\":{\"minutes\":1.48,\"words\":443},\"filePathRelative\":\"about/index.md\",\"autoDesc\":true,\"excerpt\":\"\\n<h2>关于JayChou's wiki</h2>\\n<p>本站想法源于2024年4月，无意间查到jaychou.wiki域名可以注册，便注册了域名，在思考用来做什么的时候，看到了<a href=\\\"http://sodaguide.cn/\\\" title=\\\"苏打盖\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">苏打盖</a>，随即决定对前人进行学习模仿。<br>\\n（使用了同一个开源前端框架和主题，并非copy😂）</p>\\n<h2>互联网已经存在很多资料，为什么还要费神做一个网站</h2>\\n<blockquote>\\n<p>互联网精神”即：开放、平等、协作、快速、共享。它是互联网生命力之所在，也是新经济能否发展的命脉，是其发展的关键。\\n<br>这是百度百科对互联网精神的概述和解读。</p>\\n</blockquote>\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
