import comp from "C:/Users/CYFOR/Desktop/zjl/wiki/jaychou-wiki/src/.vuepress/.temp/pages/culture/org.html.vue"
const data = JSON.parse("{\"path\":\"/culture/org.html\",\"title\":\"歌迷组织\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"歌迷组织 周杰伦吧歌迷会 成立于2003年，简称伦吧，由百度周杰伦吧发展而来，是全球最大的周杰伦粉丝聚集地，目前在全国各省会及大型城市均有分会。 自2010年起，伦吧先后进行了多次专辑团购，以及超时代、魔天伦、地表最强、嘉年华演唱会团购。 2019年主动响应清朗行动，周杰伦吧官方微博更名为「周杰伦的日常记录」，伦吧各平台账号： 微博 微信公众号：伦吧J...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.jaychou.wiki/culture/org.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"JayChou's wiki | 周杰伦百科资料集\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"歌迷组织\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"歌迷组织 周杰伦吧歌迷会 成立于2003年，简称伦吧，由百度周杰伦吧发展而来，是全球最大的周杰伦粉丝聚集地，目前在全国各省会及大型城市均有分会。 自2010年起，伦吧先后进行了多次专辑团购，以及超时代、魔天伦、地表最强、嘉年华演唱会团购。 2019年主动响应清朗行动，周杰伦吧官方微博更名为「周杰伦的日常记录」，伦吧各平台账号： 微博 微信公众号：伦吧J...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"JayChou's wiki\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"歌迷组织\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"JayChou's wiki\\\",\\\"url\\\":\\\"https://www.jaychou.wiki\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"周杰伦吧歌迷会\",\"slug\":\"周杰伦吧歌迷会\",\"link\":\"#周杰伦吧歌迷会\",\"children\":[]},{\"level\":2,\"title\":\"AllForJay周杰伦个站\",\"slug\":\"allforjay周杰伦个站\",\"link\":\"#allforjay周杰伦个站\",\"children\":[]},{\"level\":2,\"title\":\"周杰伦国际后援会 Jay2u\",\"slug\":\"周杰伦国际后援会-jay2u\",\"link\":\"#周杰伦国际后援会-jay2u\",\"children\":[]},{\"level\":2,\"title\":\"周杰伦中文网 JayCN\",\"slug\":\"周杰伦中文网-jaycn\",\"link\":\"#周杰伦中文网-jaycn\",\"children\":[]},{\"level\":2,\"title\":\"Jayme粉丝社区\",\"slug\":\"jayme粉丝社区\",\"link\":\"#jayme粉丝社区\",\"children\":[]},{\"level\":2,\"title\":\"其他\",\"slug\":\"其他\",\"link\":\"#其他\",\"children\":[]}],\"readingTime\":{\"minutes\":1.8,\"words\":539},\"filePathRelative\":\"culture/org.md\",\"autoDesc\":true,\"excerpt\":\"\\n<h2>周杰伦吧歌迷会</h2>\\n<p>成立于2003年，简称伦吧，由百度周杰伦吧发展而来，是全球最大的周杰伦粉丝聚集地，目前在全国各省会及大型城市均有分会。\\n自2010年起，伦吧先后进行了多次专辑团购，以及超时代、魔天伦、地表最强、嘉年华演唱会团购。<br>\\n2019年主动响应清朗行动，周杰伦吧官方微博更名为「周杰伦的日常记录」，伦吧各平台账号：</p>\\n<ul>\\n<li><a href=\\\"/culture/join_us.html\\\" target=\\\"_blank\\\">加入伦吧</a></li>\\n<li><a href=\\\"https://www.weibo.com/u/1806308994\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">微博</a></li>\\n<li>微信公众号：伦吧JayBar</li>\\n<li><a href=\\\"https://www.xiaohongshu.com/user/profile/648e950f000000001003496d\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">小红书</a></li>\\n<li><a href=\\\"https://tieba.baidu.com/f?kw=%E5%91%A8%E6%9D%B0%E4%BC%A6\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">贴吧</a></li>\\n</ul>\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
